require 'test_helper'

class SessionsControllerTest < ActionController::TestCase
  test "should get new" do
    get :new
    assert_response :success
  end

  test "should login" do
<<<<<<< HEAD
    dave = users(:one)
    post :create, name: dave.name, password: 'secret'
=======
    post :create, name: dave, password: 'secret'
>>>>>>> d4d83094101af40a9499369abaa4f3fe4428e6ef
    assert_redirected_to admin_url
    assert_equal dave.id, session[:user_id]
  end

  test "should fail login" do
<<<<<<< HEAD
    dave = users(:one)
    post :create, name: dave.name, password: 'wrong'
=======
    post :create, name: dave, password: 'wrong'
>>>>>>> d4d83094101af40a9499369abaa4f3fe4428e6ef
    assert_redirected_to login_url
  end

  test "should logout" do
    delete :destroy
<<<<<<< HEAD
    assert_redirected_to store_url
  end
end
=======
    assert_redirected_to :store_url
  end
>>>>>>> d4d83094101af40a9499369abaa4f3fe4428e6ef


#Commented out the below Rails autogenerated code as we have implemented some modification to session_controllers and routes
=begin
  test "should get create" do
    get :create
    assert_response :success
  end

  test "should get destroy" do
    get :destroy
    assert_response :success
  end
<<<<<<< HEAD
=end
=======
=end

end
>>>>>>> d4d83094101af40a9499369abaa4f3fe4428e6ef
